# Uncomment it when you want to download the code and deploy it directly from GitHub
# - name: Download and extract {{COMPONENT}}
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#     dest: /tmp 
#     remote_src: yes 

  
- name: Cleanup of old component 
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent
  ignore_errors: yes 

- name: Creating App Location 
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory
  ignore_errors: yes 
  become_user: "{{APPUSER}}"
  ignore_errors: yes 

# Downloads the package from NEXUS
- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: http://172.31.0.75:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_LOCATION}}"
    remote_src: yes 
  become_user: "{{APPUSER}}"


# Uncomment this only for download the code from nexus
# - name: Coping {{COMPONENT}} to {{APPUSER}}
#   ansible.builtin.copy:
#     src: /tmp/{{COMPONENT}}-main/
#     dest: /home/{{APPUSER}}/{{COMPONENT}}/
#     remote_src: yes
#   become_user: "{{APPUSER}}"
#   ignore_errors: yes